apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "13"
    meta.helm.sh/release-name: my-app
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2026-01-26T08:30:11Z"
  generation: 16
  labels:
    app.kubernetes.io/managed-by: Helm
  name: my-app-app
  namespace: default
  resourceVersion: "563494"
  uid: fee9c2ef-4283-4dee-ab4b-c6ac907e532c
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-01-27T10:15:15+02:00"
      labels:
        app: my-app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-creds
        image: 213daniel/my-python-app:v9
        imagePullPolicy: IfNotPresent
        name: python-app
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2026-01-26T08:30:12Z"
    lastUpdateTime: "2026-01-27T09:12:34Z"
    message: ReplicaSet "my-app-app-77f9b4b56" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-01-29T06:33:16Z"
    lastUpdateTime: "2026-01-29T06:33:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 16
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
